//SPDX-License-Identifier: MIT

pragma solidity > 0.8.0  <= 0.8.16;

enum PactState {
    DEPLOYED, RETRACTED, EMPLOYER_SIGNED, EMPLOYEE_SIGNED, ALL_SIGNED, ACTIVE, PAUSED, TERMINATED, RESIGNED, END_ACCEPTED, FNF_EMPLOYER, FNF_EMPLOYEE, DISPUTED, ARBITRATED, FNF_SETTLED, DISPUTE_RESOLVED, ENDED 
}