//SPDX-License-Identifier: MIT

import "hardhat/console.sol";
pragma solidity > 0.8.0  <= 0.9.0;

enum PactState {
    DEPLOYED, EMPLOYER_SIGNED, EMPLOYEE_SIGNED, ALL_SIGNED, ACTIVE, PAUSED, TERMINATED, RESIGNED, END_ACCEPTED, FNF_EMPLOYER, FNF_EMPLOYEE, DISPUTED, ARBITRATED, FNF_SETTLED, DISPUTE_RESOLVED, ENDED 
}